{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data_projext', port=443): Max retries exceeded with url: /api_1_0/conversation (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002157D05C7F0>: Failed to resolve 'data_projext' ([Errno 11001] getaddrinfo failed)\"))","children":[{"name":"test_get[caseInfo0]","uid":"dc84bc659ac0b637","parentUid":"608849b6fc95321b7b7e63890dade71e","status":"broken","time":{"start":1731765259110,"stop":1731765261847,"duration":2737},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["{'name': 'conversation查询接口', 'request': {'method': 'get', 'url': '/api_1_0/conversation', 'headers': {'token': 'token'}}, 'validate': [{'eq': ['status_code', 200]}]}"],"tags":[]}],"uid":"608849b6fc95321b7b7e63890dade71e"},{"name":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data_projext', port=443): Max retries exceeded with url: /api_1_0/conversation (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002157D458070>: Failed to resolve 'data_projext' ([Errno 11001] getaddrinfo failed)\"))","children":[{"name":"test_post[caseInfo0]","uid":"8146305b23f13402","parentUid":"e65dd195ea3780ffa20bb8dac023de16","status":"broken","time":{"start":1731765262086,"stop":1731765264777,"duration":2691},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["{'name': 'conversation添加接口', 'request': {'method': 'post', 'url': '/api_1_0/conversation', 'headers': {'token': 'token'}, 'data': {'AutoID': None, 'ConversationID': None, 'Title': None, 'Satisfaction': None, 'Evaluate_Content': None, 'Persona': None, 'Accuracy': None, 'adaptability': None}}, 'validate': [{'eq': ['status_code', 200]}, {'eq': ['code', '2000']}]}"],"tags":[]}],"uid":"e65dd195ea3780ffa20bb8dac023de16"},{"name":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data_projext', port=443): Max retries exceeded with url: /api_1_0/conversation (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000002157D259840>: Failed to resolve 'data_projext' ([Errno 11001] getaddrinfo failed)\"))","children":[{"name":"test_update[caseInfo0]","uid":"92109579f2c178d","parentUid":"9b6920a94270a7f586de6612460001ed","status":"broken","time":{"start":1731765264875,"stop":1731765267571,"duration":2696},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["{'name': 'conversation修改接口', 'request': {'method': 'put', 'url': '/api_1_0/conversation', 'headers': {'content-type': 'application/json'}, 'data': {'AutoID': None, 'ConversationID': None, 'Title': None, 'Satisfaction': None, 'Evaluate_Content': None, 'Persona': None, 'Accuracy': None, 'adaptability': None}}, 'validate': [{'eq': ['status_code', 200]}]}"],"tags":[]}],"uid":"9b6920a94270a7f586de6612460001ed"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}